package frc.robot.autos;

/** Compile-time constants for autonomous programs. */
public enum Auto {
  /** Remain idle */
  IDLE,
  TEST,
  
  BFLSTART_DEPOT_S3_TOWERLEFT,
  BLSTART_DEPOT_S3_TOWERLEFT,
  BMIDSTART_DEPOT_S3_TOWERLEFT,
  BFRSTART_OUTPOST_S2_TOWERRIGHT,
  BRSTART_OUTPOST_S2_TOWERRIGHT,
  BMIDSTART_OUTPOST_S2_TOWERRIGHT,

  BFLSTART_DEPOT_S3_LSTART,
  BLSTART_DEPOT_S3_LSTART,
  BMIDSTART_DEPOT_S3_LSTART,
  BFRSTART_OUTPOST_S2_RSTART,
  BRSTART_OUTPOST_S2_RSTART,
  BMIDSTART_OUTPOST_S2_RSTART,

  BFLSTART_DEPOT_S3_LTRENCH,
  BLSTART_DEPOT_S3_LTRENCH,
  BMIDSTART_DEPOT_S3_LTRENCH,
  BRSTART_DEPOT_S3_LTRENCH,
  BFRSTART_OUTPOST_S2_RTRENCH,
  BRSTART_OUTPOST_S2_RTRENCH,
  BMIDSTART_OUTPOST_S2_RTRENCH,
  BLSTART_OUTPOST_S2_RTRENCH,
  
  BFLSTART_DEPOT_S3_LTRENCH_ND_LTRENCH_S3_LTRENCH,
  BLSTART_DEPOT_S3_LTRENCH_ND_LTRENCH_S3_LTRENCH,
  BMIDSTART_DEPOT_S3_LTRENCH_ND_LTRENCH_S3_LTRENCH,
  BRSTART_DEPOT_S3_LTRENCH_ND_LTRENCH_S3_LTRENCH,
  BFRSTART_OUTPOST_S2_RTRENCH_NF_RTRENCH_S2_RTRENCH,
  BRSTART_OUTPOST_S2_RTRENCH_NF_RTRENCH_S2_RTRENCH,
  BMIDSTART_OUTPOST_S2_RTRENCH_NF_RTRENCH_S2_RTRENCH,
  BLSTART_OUTPOST_S2_RTRENCH_NF_RTRENCH_S2_RTRENCH,

  RFLSTART_DEPOT_S3_TOWERLEFT,
  RLSTART_DEPOT_S3_TOWERLEFT,
  RMIDSTART_DEPOT_S3_TOWERLEFT,
  RFRSTART_OUTPOST_S2_TOWERRIGHT,
  RRSTART_OUTPOST_S2_TOWERRIGHT,
  RMIDSTART_OUTPOST_S2_TOWERRIGHT,

  RFLSTART_DEPOT_S3_LSTART,
  RLSTART_DEPOT_S3_LSTART,
  RMIDSTART_DEPOT_S3_LSTART,
  RFRSTART_OUTPOST_S2_RSTART,
  RRSTART_OUTPOST_S2_RSTART,
  RMIDSTART_OUTPOST_S2_RSTART,

  RFLSTART_DEPOT_S3_LTRENCH,
  RLSTART_DEPOT_S3_LTRENCH,
  RMIDSTART_DEPOT_S3_LTRENCH,
  RRSTART_DEPOT_S3_LTRENCH,
  RFRSTART_OUTPOST_S2_RTRENCH,
  RRSTART_OUTPOST_S2_RTRENCH,
  RMIDSTART_OUTPOST_S2_RTRENCH,
  RLSTART_OUTPOST_S2_RTRENCH,
  
  RFLSTART_DEPOT_S3_LTRENCH_NF_LTRENCH_S3_LTRENCH,
  RLSTART_DEPOT_S3_LTRENCH_NF_LTRENCH_S3_LTRENCH,
  RMIDSTART_DEPOT_S3_LTRENCH_NF_LTRENCH_S3_LTRENCH,
  RRSTART_DEPOT_S3_LTRENCH_NF_LTRENCH_S3_LTRENCH,
  RFRSTART_OUTPOST_S2_RTRENCH_ND_RTRENCH_S2_RTRENCH,
  RRSTART_OUTPOST_S2_RTRENCH_ND_RTRENCH_S2_RTRENCH,
  RMIDSTART_OUTPOST_S2_RTRENCH_ND_RTRENCH_S2_RTRENCH,
  RLSTART_OUTPOST_S2_RTRENCH_ND_RTRENCH_S2_RTRENCH,
}
