package frc.robot.autos;

/** Compile-time constants for autonomous programs. */
public enum Auto {
  /** Remain idle */
  IDLE,
  TEST,
  
  FLSTART_DEPOT_S3_TOWERLEFT,
  LSTART_DEPOT_S3_TOWERLEFT,
  MIDSTART_DEPOT_S3_TOWERLEFT,
  FRSTART_OUTPOST_S2_TOWERRIGHT,
  RSTART_OUTPOST_S2_TOWERRIGHT,
  MIDSTART_OUTPOST_S2_TOWERRIGHT,

  FLSTART_DEPOT_S3_LSTART,
  LSTART_DEPOT_S3_LSTART,
  MIDSTART_DEPOT_S3_LSTART,
  FRSTART_OUTPOST_S2_RSTART,
  RSTART_OUTPOST_S2_RSTART,
  MIDSTART_OUTPOST_S2_RSTART
}
