package frc.robot.autos;

/** Compile-time constants for autonomous programs. */
public enum Auto {
  /** Remain idle */
  IDLE,
  TEST,
  
  FLSTART_DEPOT_S3_TOWERLEFT,
  LSTART_DEPOT_S3_TOWERLEFT,
  MIDSTART_DEPOT_S3_TOWERLEFT,
  FRSTART_OUTPOST_S2_TOWERRIGHT,
  RSTART_OUTPOST_S2_TOWERRIGHT,
  MIDSTART_OUTPOST_S2_TOWERRIGHT,

  FLSTART_DEPOT_S3_LSTART,
  LSTART_DEPOT_S3_LSTART,
  MIDSTART_DEPOT_S3_LSTART,
  FRSTART_OUTPOST_S2_RSTART,
  RSTART_OUTPOST_S2_RSTART,
  MIDSTART_OUTPOST_S2_RSTART,

  FLSTART_DEPOT_S3_LTRENCH,
  LSTART_DEPOT_S3_LTRENCH,
  MIDSTART_DEPOT_S3_LTRENCH,
  RSTART_DEPOT_S3_LTRENCH,
  FRSTART_OUTPOST_S2_RTRENCH,
  RSTART_OUTPOST_S2_RTRENCH,
  MIDSTART_OUTPOST_S2_RTRENCH,
  LSTART_OUTPOST_S2_RTRENCH,
  
  FLSTART_DEPOT_S3_LTRENCH_ND_LTRENCH_S3_LTRENCH,
  LSTART_DEPOT_S3_LTRENCH_ND_LTRENCH_S3_LTRENCH,
  MIDSTART_DEPOT_S3_LTRENCH_ND_LTRENCH_S3_LTRENCH,
  RSTART_DEPOT_S3_LTRENCH_ND_LTRENCH_S3_LTRENCH,
  FRSTART_OUTPOST_S2_RTRENCH_NF_RTRENCH_S2_RTRENCH,
  RSTART_OUTPOST_S2_RTRENCH_NF_RTRENCH_S2_RTRENCH,
  MIDSTART_OUTPOST_S2_RTRENCH_NF_RTRENCH_S2_RTRENCH,
  LSTART_OUTPOST_S2_RTRENCH_NF_RTRENCH_S2_RTRENCH,

  FLDUMMYSHOOT,
  LDUMMYSHOOT,
  MIDDUMMYSHOOT,
  RDUMMYSHOOT,
  FRDUMMYSHOOT,

  FLSTART_S3_DEPOT_S3,
  LSTART_S3_DEPOT_S3,
  FRSTART_S3_DEPOT_S3,
  RSTART_S3_DEPOT_S3,

  FLSTART_NA_S3_DEPOT_S3
}
